"""empty message

Revision ID: 3c2377e2b032
Revises: 
Create Date: 2021-02-14 20:01:53.821088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c2377e2b032'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_location_name'), 'location', ['location_name'], unique=True)
    op.create_table('oggetto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_name', sa.String(length=64), nullable=True),
    sa.Column('object_notes', sa.String(length=300), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oggetto_object_name'), 'oggetto', ['object_name'], unique=True)
    op.create_index(op.f('ix_oggetto_object_notes'), 'oggetto', ['object_notes'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oggetto_object_notes'), table_name='oggetto')
    op.drop_index(op.f('ix_oggetto_object_name'), table_name='oggetto')
    op.drop_table('oggetto')
    op.drop_index(op.f('ix_location_location_name'), table_name='location')
    op.drop_table('location')
    # ### end Alembic commands ###
